### ISSUE TITLE
How to re-run clustering with singularity install?

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [wheaton5/souporcell#10]
Hello again!

Potentially naive question here -- If I ran SoupOrCell using the suggested singularity install, how can I run specific parts of the pipeline as you describe in the 'hard-install' section? I just applied the pipeline to a new dataset but realized I set the wrong k and want to just re-do the clustering step.

Thanks again for the new tool -- it is extremely useful!!!

Chris

**Comment by wheaton5** [comment]
You should be able to delete the <stepname>.done file and rerun it. But I would recommend that if you rerun one part, you should rerun everything downstream. So if you rerun clustering, you should  rerun doublet detection and ambient rna estimation/genotyping. So that will be clustering.done, troublet.done, consensus.done. 

Also you can run these tools individually similar to my hard-install section except through the singularity container (I should update the docs more). All you have to do is run singularity exec souporcell.sif command where command might be souporcell.py or troublet (you can see the examples I have in the hard install section, but using the singularity container it will be no installation!)

Also its all lowercase souporcell lol. And pronounced as "super cell" just spelled differently lol.

**Comment by chris-mcginnis-ucsf** [comment]
Sweet! Will let you know if I run into any issues.

And duly noted -- we here in the Bay Area are big fans of extraneous capitalizations :)

**Comment by wheaton5** [comment]
I will close this for now. Feel free to reopen if you had any issues.
