### ISSUE TITLE
How to set parameters for high doublet percentage

### ISSUE THREAD

**Issue by mary77** [wheaton5/souporcell#117]
I am testing souporcell on a dataset which has 40% doublets. When I exclude doublets the performance is pretty good but after including them performance decreased dramatically. Is there any parameter that I need to set to identify more doublets? Something like doublet_threshold!

**Comment by wheaton5** [comment]
So is this like superloading cells into the experiment?

**Comment by mary77** [comment]
Yes I think its super loaded. The ARI vs hashtag excluding doublets is 0.97 but its 0.53 after including doublets.

Thank you for the prompt response

**Comment by wheaton5** [comment]
Yeah, I don't think it will cope with that level of superloading. It's just not built for that. I don't think any simple parameter change will make it work well. So just exclude doublets already called.

**Comment by mary77** [comment]
So its just benchmarking on a dataset with true labels form hashtag to see how it works. After doing actual experiment (without hashtag)  I do not have doublet labels to exclude them. 
Our lab wants to use souporcell instead of hashtaging for upcoming experiments. What is the reasonable doublet rate that souporcell can handle?

**Comment by wheaton5** [comment]
I would not load more than 20k cells. Really 5-10k is better. And sequence them fairly deep. Like >4k median UMI/cell. More is better. Better to get good data than have to redo experiments.

**Comment by wheaton5** [comment]
If it is a human sample you can use the common variants file provided. And also you get some better performance with HISAT2 as the remapper, but you have to install that yourself. Due to licensing issues with GPL I do not include it in the singularity build. How many individuals are you mixing? The clustering becomes much harder as the number of individuals increases. I like to use a max of 8 individuals. Also something you could try is running another doublet detector and excluding doublets before souporcell. Souporcell uses only the genotypes for doublet detection after clustering, but doublets also make the clustering harder. I suggest Solo over doubletfinder, but you could use both as well.

**Comment by mary77** [comment]
Thank you so much for the detailed guideline and very helpful information. I didn't know about the --aligner option.  I will give it a try.

The experiment is human sample and the number of individuals I think might be 12 but there are 3 different wells which means 4 individuals for each well.  I am running souporcell for each well separately. Am I correct?
