### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by VincentGardeux** [wheaton5/souporcell#13]
Hello,

I recently installed souporcell, using the singularity installation. The version should be fine given the following:

```
singularity --version
singularity version 3.2.1-1.1.el7
```

However, when running souporcell, I receive the following error, just after the "checking modules":

```
checking modules
SIGILL: illegal instruction
PC=0x473b8b m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x5a32, 0x4, 0x0, 0xc000299ef0, 0x4907b2, 0x5a32)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000299eb8 sp=0xc000299eb0 pc=0x473b8b
syscall.Kill(0x5a32, 0x4, 0x438a2e, 0xc000299f20)
        /usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000299f00 sp=0xc000299eb8 pc=0x47053b
github.com/sylabs/singularity/internal/app/starter.Master.func4()
        internal/app/starter/master_linux.go:158 +0x3e fp=0xc000299f38 sp=0xc000299f00 pc=0x8e27be
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
        internal/pkg/util/mainthread/mainthread.go:20 +0x2f fp=0xc000299f60 sp=0xc000299f38 pc=0x8819cf
main.main()
        cmd/starter/main_linux.go:102 +0x68 fp=0xc000299f98 sp=0xc000299f60 pc=0x8e2ff8
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:201 +0x207 fp=0xc000299fe0 sp=0xc000299f98 pc=0x430cd7
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000299fe8 sp=0xc000299fe0 pc=0x45c7f1

goroutine 5 [syscall]:
os/signal.signal_recv(0xab4480)
        /usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc00015b150)
        internal/pkg/util/mainthread/mainthread.go:23 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x4, 0x5, 0x1d00, 0x5a45, 0xc00000cb00)
        internal/app/starter/master_linux.go:157 +0x44e
main.startup()
        cmd/starter/main_linux.go:73 +0x563
created by main.main
        cmd/starter/main_linux.go:98 +0x3e

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x5a32
rsi    0x4
rbp    0xc000299ef0
rsp    0xc000299eb0
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0xc
r13    0xff
r14    0xaa90fc
r15    0x0
rip    0x473b8b
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by wheaton5** [comment]
Thanks for your interest. Can you let me know what your command is?

Best,
Haynes

**Comment by VincentGardeux** [comment]
Hi, sure, here it is:

`singularity exec souporcell.sif souporcell_pipeline.py -i /data/output_RNA_hg3775/outs/possorted_genome_bam.bam -b /home/selected_cells_2300.txt -f /data/genome/10x/GRCh37.75/fasta/genome.fa -o /data/output_souporcell -k 22 -t 2`

**Comment by wheaton5** [comment]
Sorry, I'm not able to recreate this error so I'm thinking how best to test it. It seems very likely to be in the loading of one of the python packages as I print "imports done" after importing everything and none of my code is in go (error from golang). Looking at the import list, seems most likely coming from tensorflow (golang coming from google, as does tensorflow). 

Could you try 
singularity exec souporcell.sif python
then
import tensorflow

If that doesn't produce the error, could you try the same with each package in 

import numpy as np
import tensorflow as tf
import scipy
import gzip
import math
import pystan
import vcf
import pysam
import pyfasta
import subprocess
import time
import os

We might be dealing with a hardware issue I'm not sure. But perhaps a different version of tensorflow would work for you (I'm working with tensorflow 1.18 functionality but by default installing tensorflow 2.blah which has tons of updates).

**Comment by VincentGardeux** [comment]
Hi again,

Yep you pinpointed the error correctly.
All the imports are working well except the import of tensorflow, which generates the exact same error.
Is there something I can do? Since I cannot regenerate an image myself for singularity?

Thanks

**Comment by wheaton5** [comment]
Looks like your CPU is old (sorry, I don't mean that disparagingly).

According to https://github.com/tensorflow/tensorflow/issues/18275 you will need tensorflow 1.5. I'm not sure if my code is compatible with that or not. 

I am hoping to move away from tensorflow entirely soon, but probably not soon enough to solve your issue.

What I can do is I can try to make a version for you with tf 1.5 and see if it works or not. I don't want to move the standard container to use that as there are significant speedups the newer versions have.

The other thing we should probably discuss is your dataset and runtimes and expectations etc etc. So you are trying to cluster 22 donors. This is at the edge and perhaps a bit beyond what souporcell is currently capable of doing. The issue is that the more clusters there are, the more local minima there are. The standard way of getting over local minima in clustering is just to restart multiple times and take the best solution (lowest total loss value). The default restarts for souporcell is 15. For 22 clusters I would suggest going up to 30 or so restarts. Okay, maybe that is okay, maybe not. I have several ideas on how to make souporcell work better on higher numbers of donors, but have not implemented or tested them yet. We have tested on up to 8 donors for real data and up to 20 donors for simulated data. And also, you have set the number of threads to be 2. For the remapping and various read level manipulation required, this will take quite a long time. And it will also take a long time for the clustering. I would suggest that you use the --skip_remap True and the --common_variants options to be able to have faster runtime and high quality variants. But even so, in the current state of things I would expect this to take a long time. I also have plans that should dramatically speed up clustering (and drop tensorflow at the same time), but that will be a few weeks from now.

I will post here again in a while with a tf 1.5 version if it accepts the syntax/function calls I use (tho not fully tested).

**Comment by wheaton5** [comment]
So here it is. Once again this isn't fully tested.
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=15cnsg0AloQwFPFNpg3imgc_p-_qkwnOF' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=15cnsg0AloQwFPFNpg3imgc_p-_qkwnOF" -O souporcell.sif && rm -rf /tmp/cookies.txt
```
But keep in mind my other suggestions. The main update I want to make I have a prototype working on another algorithmically related project tho entirely different application and the optimization is very fast (which will allow for vastly more restarts overcoming local minima) and doesn't require tensorflow. But I have another project and am leaving on vacation tomorrow so it will be a few weeks for implementation + testing, but I am very confident the new approach will be better. Please share more about your application. I am very motivated by such stories lol.

Best,
Haynes

**Comment by VincentGardeux** [comment]
Thanks a lot for the detailed answer.

Unfortunately, the new image is not helping, and the same error message keeps coming when I import tensorflow.
I double-checked that the version of the package was different using pip freeze and it says:
```
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
```

So I guess even this version is too recent.
It's true that the CPU is a bit old (~10yrs)

Cheers

**Comment by VincentGardeux** [comment]
Ok so with a "Hard Install" of all the tools/packages, and using tensorflow 1.5 it now works
So indeed it was just tensorflow version that was the culprit

Thanks for the help, and I am looking forward your new version :)
