### ISSUE TITLE
Additional ambient RNA/soup information

### ISSUE THREAD

**Issue by royoelen** [wheaton5/souporcell#14]
Would it be possible to get information about the supposed ambient RNA/soup in our experiment, as reported by the file created with the --soup_out parameter when creating the conscensus? Such as the SNPs called in this soup?

We are having some demultiplexing troubles in one of our experiments, and as this tool seems to do more conservative doublet calling, we are interested if and how this 'soup' might be related to the genotype/doublet calling in our experiments/tools

**Comment by wheaton5** [comment]
So the doublet calling does not explicitly model the ambient RNA, but implicitly accounts for the soup because it uses the allele fractions in each cluster and the clusters already contain the alleles from the ambient RNA. I wouldn’t say that we are conservative in doublet calling. I would say that demuxlet is overly aggressive in doublet calling as it doesn’t account for ambient rna at all. I would take a look at figure 2 of our paper one panel shows roc curves of doublet calls across tools for a synthetic mixture (known doublets) and 10% ambient rna. However, If the doublet calling isn’t working well, the ambient RNA estimation will be dramatically inflated as doublets are excluded for that calculation. If you give me some more specifics about your problems I might be able to provide more insight. I’m on vacation right now so may be a bit slow to reply. Apologies in advance.

**Comment by wheaton5** [comment]
The other thing I wanted to add about this was that currently no specific alleles are attributed to ambient RNA, but I suppose that we could use the genotype calls (which happen in conjunction with the ambient RNA estimation) to give some confident calls of alleles arising from ambient RNA. For instance, when we have confidently called a variant for a cluster homozygous, then all of the alleles coming from the other allele can be assumed to be either errors or from ambient RNA. But at the same time, there will be a contribution from the ambient RNA of the expected allele. We can give an estimate of what % of those alleles come from ambient RNA and which come from the true cells, but we can't say which specific reads they came from. Not sure if this answers your question, but I hope it helps.

**Comment by Neleor** [comment]
Thank you very much, this is enough info for now.

**Comment by royoelen** [comment]
Thank you very much, this is enough information for me for now.
