### ISSUE TITLE
Singularity build for v2.0

### ISSUE THREAD

**Issue by achamess** [wheaton5/souporcell#22]
Is the singularity image download on the main page for v1.0 or has it been updated to v2.0? I'd like  to run the latest version, if possible.

**Comment by wheaton5** [comment]
It is now. Sorry for the delay. Busy with other project. And I wanted to get all features from previous version in new version. Currently still lacking --known_genotypes (well, option is still there but it will fail, oops). --common_variants still works as it is entirely upstream of the clustering process. And I haven't gotten your cell assignment initialization done either, but that should be pretty easy.

Basic version report:
Clustering method completely reimplemented in Rust. This along with the algorithm changes gives me several advantages to speed and memory usage as well as ragged array support which allows me to use all data without going way high in memory --max_loci option no longer used (tho have not deleted as an option, TODO)
New clustering method using expectation maximization with deterministic annealing greatly improves the ability to overcome local optima with high number of donors. This method also allows us to use the binomial pdf loss function instead of the sum of squared differences loss function. So now all values are log likelihoods and not log loss.
Doublet detection improved by using the same statistical urn problem setup, but then iteratively removing detected doublet cell's alleles from the singlet cluster urns and then looking for doublets again until we no longer find new doublets.
--known_genotypes currently not supported TODO.
shared_samples.py script now available to show which clusters correspond to which other clusters in experimental designs involving multiple experiments with overlapping samples
various bug fixes

**Comment by achamess** [comment]
Got it. Thanks! Worked perfectly out of the box.
