### ISSUE TITLE
maximum number of K?

### ISSUE THREAD

**Issue by notimenocall** [wheaton5/souporcell#30]
Hi,
Thanks for developing the tool! I just have a quick question about what is the max number of K ever tested? What would be the technical limitations for increasing K? I am planning on an experiment and would like to know how many samples I can mix.

**Comment by wheaton5** [comment]
Hi,

The two issues are signal to noise and local maxima in the optimization process. I have tried up to 21. How reliable it is up to that point depends on the amount and quality of the data.

For signal to noise, the biggest factor is amount of data. If your cells have lots of RNA and you use nextgem/v3 chemistry (higher library complexity) and sequence to saturation, you may have 50k UMI/cell. But most scRNAseq experiments are more in the 2-4k UMI/cell range in my experience. At this range with human levels of variation, 20 is already pushing it. With lots of data, going up to 30 or mayyybe 40 may be possible.

But local optima in the optimization is also a problem. Souporcell uses a deterministic annealing version of expectation maximization to help get around this. This makes souporcell much more robust to local optima than, say, kmeans clustering. As a test I have generated sample 2d data with very well separated 30 clusters and run kmeans on it. Even with 10,000 random restarts, kmeans does not get the optimal solution (usually 2-6 clusters are combined with other clusters while other single clusters are split into multiple clusters). I say this just to demonstrate that this is a hard problem with "cluster center" based approaches. There are other clustering approaches, but due to the sparsity of scRNAseq variant data, a cluster center approach works the best (as evidenced by all 3 published algorithms for this problem using a cluster center approach... and a previous failed attempt by me to make a graph based clustering version).

My personal opinion is that you want your experiments to be robust such that you can trust the clusterings and the inferences you make about your data. Otherwise it is a waste of time. Going from 16 donors to 32 donors only halves the number of experiments you need to do, but may endanger the quality of the results. If I were designing experiments, I would limit myself to 16 multiplexed samples.

I hope this helps.

Best,
Haynes

**Comment by notimenocall** [comment]
Very helpful explanation.  Thank a lot!
