### ISSUE TITLE
Memory and Time Difference

### ISSUE THREAD

**Issue by drneavin** [wheaton5/souporcell#34]
Hello,

I have run souporcell with both the pipeline script as well as running each step individually. I have noticed that running each step separately takes significantly more time and memory to run. For example, when I run the pipeline script it takes about 3 hours and 30G of memory but when I remap using
```
python renamer.py --bam possorted_genome_bam.bam --barcodes barcodes.tsv --out fq.fq

minimap2 -ax splice -t 8 -G50k -k 21 -w 11 --sr -A2 -B8 -O12,32 -E2,1 -r200 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g2000 -2K50m --secondary=no <reference_fasta_file> <fastq_file> > minimap.sam

python retag.py --sam minimap.sam --out minitagged.bam
```
I have already used ~8 hours and ~30G of memory. Do you have recommendations on how to enhance the speed and memory when running step by step? 

Thank you for your help and recommendations!

**Comment by wheaton5** [comment]
For the renamer / mapping / retag steps, the pipeline parallelizes the renamer and retag steps by working on chunks of the original bam and outputing multiple fastqs then mapping each fastq independently and retagging each mapped bam before merging. I should maybe put that parallelism machinery in the individual scripts and have the pipeline just indicate how many cores each script should use. The 30G is almost all due to the minimap index creation. I could provide indexed references for human and use the minimap command to use one of those instead of creating the index on the fly and that would reduce the memory requirements of these steps to <6G. 

For later steps, my documentation is out of date for the step by step running. Is there a reason you don't want to use the pipeline? It is set up such that if it fails or you stop it at any point, rerunning it on the same output directory will continue from the last completed step. You can also delete some but not all of the <stage_name>.done files and rerun on the same directory and it will redo those stages. I will work on updating the docs for now.

**Comment by wheaton5** [comment]
Ok I have updated the documentation of step by step running to reflect the current code/recommendations. And I have provided a conda env yaml file for you to easily get the right versions of python packages.

Updating the renamer/retag steps to be parallel will take more time and testing. I recommend you run the pipeline at least for those stages for now.

**Comment by wheaton5** [comment]
You also might be interested in skipping the remapping stages (some of the most time and memory intensive stages) if you have a common variants file for your species such as the 1k genomes vcf for human. In fact even running with skip remap without common variants for human works well with good data (umi/cell > 4k).

**Comment by wheaton5** [comment]
I am going to close this. Feel free to reopen if you need more help.
