### ISSUE TITLE
How to debug large number of unassigned cells?

### ISSUE THREAD

**Issue by mxposed** [wheaton5/souporcell#36]
Hello Haynes,

In one of the samples I have a quite high number of unassigned cells. If I get it right from the code, unassigned means that posterior probability of it belonging to one of the genotypic clusters or of being a doublet of any pair is not high enough.
In this sample we expect 2 or 3 genotypes, so I first ran souporcell with k=2 and got ~2k out of ~7k cells as unassigned. Then I reran it with k=3, and (to my surprise) got ~2.5k cells as unassigned.
Two questions related to that:
1. How to debug this situation?
2. Could the problem be in the cluster definition? Would running the mixture model clustering more times help?

Thank you for the great tool,
Best,
Nick

**Comment by wheaton5** [comment]
Hi Nick,

Could you give me more information about the experiment? What organism? How many UMI/cell. Do you expect the individuals to be related?

In general I see unassigned cells due to 2 or 3 reasons. 1. low UMI/cell (<4k causes slight problems <2k starts to be very difficult), 2. related individuals (problems occur at higher UMI count than unrelated individuals) and 3. large K, many individuals in a mixture greatly increase the number of possible doublet combinations. 

You are correct that a poor clustering will also cause this, but for k=2 or 3 I've really never seen the clustering fail with sufficient data.

If you could give any potentially relevant information I might be able to help more.

Best,
Haynes

**Comment by wheaton5** [comment]
Following up via email ongoing, closing issue
