### ISSUE TITLE
Using bulk RNA-seq to match identity with souporcell calls

### ISSUE THREAD

**Issue by achamess** [wheaton5/souporcell#41]
Hi again. So souporcell worked nicely to cluster my snRNA-seq data into different donors. But now I need to go back and match the donor with the souporcell call. I've done regular bulk RNA-seq on each individual donor. Is there a good way now to use that bulk RNA-seq data to see which donor corresponds to each cluster?

**Comment by wheaton5** [comment]
I think my shared_samples.py script should be able to do it if you put things in a particular format. Otherwise you might be able to reuse some of that code.

If you do population variant calling (or combine individual GVCFs then convert back to vcf) to create a population vcf from the bulk RNAseq, you should be able to put that in a directory and call it souporcell_merged_sorted_vcf.vcf.gz and tell it --shared is the total number of donors (k) then it should tell you which ones are which. So to be clear shared_samples.py will take as input the directory of the souporcell output as well as the directory you put the population vcf of the bulk RNAseq as well as the total number of donors.

Let me know if you have any problems. With some time I could write something which generalizes shared_samples.py to be able to take multiple vcfs instead of a population vcf.

**Comment by achamess** [comment]
Thank @wheaton5 
What software package would you recommend for calling the variants? The same you use for soupocell? And by population, do you mean combining all the donor RNA-seq files into one? I'd still need to have some identifying info in there, probably in a bam tag or something? Sorry for the noob questions.

> Let me know if you have any problems. With some time I could write something which generalizes shared_samples.py to be able to take multiple vcfs instead of a population vcf.

I wouldn't object. I suspect others may use too. I'm curious to see how reviewers deal with people using demux software like souporcell or demuxlet. Ultimately, most would want you to map back to a donor so you can see the patient characteristics. Or in my case, one sample looked different than the others, and now I need to know why.

**Comment by wheaton5** [comment]
You have to add read groups to your bams before variant calling. You wouldn't need vartrix as you don't have cell barcodes. So you can just use freebayes. 

EKG has a tool to add read groups and merge bams at the same time.
https://github.com/ekg/bamaddrg
and it is streaming so can pipe directly into freebayes if you don't want to keep the merged bam.

Prior to that you need to consider what mapping is done. The STAR alignments aren't very good for variant calling. I would recommend HISAT-2 or minimap2 (won't do splicing right, but will soft clip things appropriately and not have spurious alignments so will be specific but not as sensitive).

It's gonna be at least a week before I can do anything on this myself as I have several deadlines coming up. Even when/if I do it, I think I will require GVCF files which can just be combined into a population vcf anyway. The problem with multiple vcfs is that when a variant locus isn't in one vcf is that because there was no data at that site or because it was all reference?

**Comment by wheaton5** [comment]
So yeah the other way to go about this is to generate GVCFs for each bam and combine them into a population vcf so on freebayes --gvcf and then combine them (all I can find is https://gatk.broadinstitute.org/hc/en-us/articles/360037053272-CombineGVCFs although I avoid gatk when possible). 

Oh maybe https://github.com/sequencing/gvcftools
has merge_variants (merges multiple GVCF files) and extract_variants (GVCF -> vcf)

**Comment by TaurVil** [comment]
Hello, very useful to have this explained here! 

I'm wondering if you have any advice for understanding an interpreting the output of shared_samples.py. In this case, I know there are 6 individuals in each set. Should I pick the first six options which minimize the loss (and what exactly does that refer to? 

![image](https://user-images.githubusercontent.com/41305538/114044141-8e768300-984c-11eb-8da8-e17120ca55d6.png)
