### ISSUE TITLE
using souporcell for plate-based scRNA-seq (Celseq2)

### ISSUE THREAD

**Issue by dwkarjosukarso** [wheaton5/souporcell#52]
Hi, 
I am thinking of trying to use the tool to demultiplex sequences from a mixed population of 5 donors. However, our lab uses plate-based scRNA-seq (Celseq2) and therefore we also don't cannot estimate how many of e.g. donor 1 is sorted into plate 1, etc.
Do you have any recommendation on how to modify souporcell for plate-based data?
Thanks!

Dyah

**Comment by wheaton5** [comment]
Souporcell doesn't require an estimated proportion of each donor. Depending on the nature of the data, souporcell might work just fine.

Is there a UMI? If it is not tag UB, then use option --umi_tag to set it. If there is no umi, use option --no_umi True. How about cell tag? Often these plate based things have 1 bam per cell. You will need to combine these and make a cell barcode (CB) tag for each cell and put that tag in all the reads associated with that cell. I have some code for this if you are interested I'll dig it up. 

Otherwise, assuming there are enough cells and enough data per cell, souporcell should work.

**Comment by dwkarjosukarso** [comment]
so, I've managed to get 1 bam file per plate with UB tag for UMI and CB tag for cell barcode_sequencing index, so I can merge the bam files of same sample but different plate (alignment was done using bowtie2). 
Would I need to remap this using minimap or better start from the fastq?

What is assumed as enough cells and enough data per cell? We typically have 3 x 384 -WP per sample and sequence 30 M reads per plate.

**Comment by wheaton5** [comment]
So if you have such a bam, you can let the souporcell_pipeline.py do the remapping for you. Or if you trust bowtie2 for variant calling, you could use the --skip_remap True option. I recommend doing this only if you use a --common_variants file such as the 1kgenomes file I provide on my README assuming this is human. 

So that is a reasonable number of cells and more reads per cell than we get with droplet technologies (generally we get 2k-35k UMIs per cell) and you have 78k reads per cell. Assuming a good % of those are not duplicates, then it should be good.
