### ISSUE TITLE
VCF problems

### ISSUE THREAD

**Issue by Balthasar-eu** [wheaton5/souporcell#56]
Hi, I installed Souporcell and ran it on the example data and some of our actual data, but noticed some problems with the resulting vcf file:

1. When using VCFtools with the vcf file it fails because the sample names cannot be "0". The issue seems to be the last line of the header of the vcf file, where the clusters are enumerated starting with 0.

2. The quality field in the output vcf for the loci has values that can't be Phred quality scores, as they go below 1 and into high thousands. The VCFv4.2 specification says this field should contain a Phred score and I didn't find an indication in the tool documentation that that there was a deriviation from the standard, so I assume this is not intended?

For reference, here is the last line of the header and the first two lines of data from the run I did on the example dataset referenced in the github readme, where both issues can be observed.

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	0	1	2	3
1	14677	.	G	A	6.51758	.	NS=1;DP=124;DPB=124.0;AC=1;AN=2;AF=0.5;RO=99;AO=25;PRO=0.0;PAO=0.0;QR=3747;QA=934;PQR=0.0;PQA=0.0;SRF=99;SRR=0;SAF=25;SAR=0;SRP=217.986;SAP=57.2971;AB=0.201613;ABP=98.9053;RUN=1;RPP=57.2971;RPPR=217.986;RPL=0.0;RPR=25.0;EPP=57.2971;EPPR=217.986;DPRA=0.0;ODDS=1.24845;GTI=0;TYPE=snp;CIGAR=1X;NUMALT=1;MEANALT=1.0;LEN=1;MQM=36.76;MQMR=37.1111;PAIRED=0.0;PAIREDR=0.0	GT:AO:RO:T:E:GO:GN	0/0:0:15:-5:-27:-1,-70,-11:0,-68,-10	0/0:0:9:-5:-27:-1,-42,-7:0,-41,-6	0/1:3:2:-5:-27:-12,-8,-2:-10,-5,0	1/1:8:0:-5:-27:-37,-1,-6:-36,0,-5
1	629218	.	A	G	2.41084e-14	.	NS=1;DP=56;DPB=56.0;AC=0;AN=2;AF=0.0;RO=53;AO=3;PRO=0.0;PAO=0.0;QR=1998;QA=105;PQR=0.0;PQA=0.0;SRF=53;SRR=0;SAF=3;SAR=0;SRP=118.098;SAP=9.52472;AB=0.0;ABP=0.0;RUN=1;RPP=9.52472;RPPR=78.766;RPL=0.0;RPR=3.0;EPP=9.52472;EPPR=78.766;DPRA=0.0;ODDS=57.925;GTI=0;TYPE=snp;CIGAR=1X;NUMALT=1;MEANALT=1.0;LEN=1;MQM=40.0;MQMR=38.9623;PAIRED=0.0;PAIREDR=0.0	GT:AO:RO:T:E:GO:GN	0/1:1:3:-9:-11:-4,-13,-2:-2,-11,0	0/0:1:8:-9:-11:-3,-35,-5:0,-31,-1	0/1:1:3:-9:-11:-4,-13,-2:-2,-11,0	0/1:1:1:-9:-11:-5,-4,-1:-3,-3,0
```

Edit:
I installed Souporcell via the "hard Linux install", as we do not have Singularity installed on our severs.

Unrelated to that, but it is also possible to get the ref/alt information for each cell individually?

**Comment by wheaton5** [comment]
Hi Balthasar,

Thanks for your interest.

1. All I see in the VCFv4.2 spec about sample names is the following "If genotype data is present in the file, these are followed by a FORMAT column header, then an arbitrary number
of sample IDs. Duplicate sample IDs are not allowed. The header line is tab-delimited." But I am happy to add "cluster" before "0" etc if that fixes parsing in common tools.

2. The QUAL data is just carried over from freebayes or from the common_variants or known_variants vcf input. The numbers you mention are all proper phred scores. These phred scores are in such a wide range because we have a mixture of individuals potentially at very skewed mixtures so you might have a true variant that is at a very low allele fraction which freebayes will report but won't give a high quality. Likewise some variants will be perhaps homozygous alt in all samples and get a very high qual. Very high qual's aren't really realistic as there is some cap on how sure you should be able to be, but again it's just passed on from freebayes. The GO/GN fields in the format section are the genotype log likelihoods and the genotype log posteriors for 0/0, 0/1, 1/1 genotypes for that cluster.

3. The alt.mtx and ref.mtx contain all counts for each cell in a matrix market format. After the first 3 lines, the first column is the locus (1 indexed index of line in the vcf file), second column is cell number (1 indexed from the barcodes.tsv file), and the 3rd column is the allele count (alt for alt.mtx, ref for ref.mtx)

I hope this helps. I'll fix that cluster name issue soon.

**Comment by Balthasar-eu** [comment]
Hi wheaton5,

To 1. I looked it up again, and it was Plink that complained about the name being zero, not vcftools. 

2. That makes sense, thanks for clarifying and thanks for the answer for 3 as well!
