### ISSUE TITLE
how to get a genotype x cell matrix?

### ISSUE THREAD

**Issue by LuyiTian** [wheaton5/souporcell#67]
I checked the output of the file and it seems `alt.mtx` is the matrix of alternative allele count where rows are candidite variations and columns are cell. but the file is a sparse matrix without column and row names. So I dont know how to connect each row to a certain genomic position.

**Comment by wheaton5** [comment]
So there is a ref.mtx and an alt.mtx following the matrix market format https://math.nist.gov/MatrixMarket/formats.html#MMformat. After the header (first 3 lines) the first value is the row number (1 indexed). The second is the cell number (also 1 indexed). The 3rd value is the number of alt or ref alleles seen for that variant and that cell. Values where both ref and alt are 0 are excluded. The row number can be associated with variants by looking at the input vcf record number. So the first line after the line with "#CHROM  POS     ID      REF     ALT..." will be locus 1 in the matrix market format. And likewise the cell number is taken from the ordering of the barcodes.tsv file. So the first like will be cell 1 in the matrix market format. The one complicated thing is which vcf is the input vcf. If you used common variants or known variants, those will make a common_variants_covered_tmp.vcf which is the input to vartrix and will give you the correct variants for the matrix files. Otherwise, the output of freebayes will be the input and that should be called souporcell_merged_sorted_vcf.vcf.gz.

I hope this helps.

Best,
Haynes

**Comment by LuyiTian** [comment]
@wheaton5 What I actually want to do is to find the SNPs for each individuals from the result and use them to align individuals in multiple samples, such as sample1 contains patient1 and 2, sample2 contains patient1 and3. patient1 is shared between sample 1 and 2 so ideally we could detect it. But when I checked the genotype specified at `cluster_genotypes.vcf` I found many overlaps to both individuals on both samples.

Then I found an undocumented script: https://github.com/wheaton5/souporcell/blob/c130c2735dee6942f8fcc79fcc7a92296519efbb/shared_samples.py

Is that the script that dealing with such problems?

**Comment by wheaton5** [comment]
If you have multiple overlapping experiments, yes that is the script you want to use. You should be able to figure it out from the usage.

**Comment by LuyiTian** [comment]
OK we gave it a try, with input the same as the example I proposed.  and this is the output I got:

`locus1 matchset 8171
cell clusters 6919
cell clusters 5537
clusters for experiment1 2
clusters for experiment2 2
experiment1_cluster	experiment2_cluster	loss
1	1	76.58698751554466
0	0	618.1131036789877
1	0	817.4982753910363
0	1	823.6211197355218`

It printed out a few more lines because I dont know what that means so I deleted them:
`    if index >= args.shared*2:
        break`

So I guess individual1 from experiment1 and individual1 from experiment2 are the same person?

**Comment by LuyiTian** [comment]
thank you for your help.

**Comment by wheaton5** [comment]
Sorry, this slipped through and I didn't see it until now. You are expecting the two experiments to overlap in 1 sample I assume? Then yes, cluster 1 in both experiments are the same person. But if you expected them to overlap in 2 people, it doesn't appear that cluster 0 is the same person in each based on those loss values.

**Comment by LuyiTian** [comment]
Yes we have demultiplexed and identified all patients using this script. It is useful and you should highlight it in the documentation. 

BTW it is a large COVID cohart, so your method has contribute to the COVID19 research. Thank you.

**Comment by wheaton5** [comment]
Nice! Yes I will add it to the docs. I do mention it in the paper but pretty briefly when explaining table 1 and overlapping mixtures to identify which patient is which.
