### ISSUE TITLE
Number of SNPs assigned to each genotype

### ISSUE THREAD

**Issue by vertesy** [wheaton5/souporcell#78]
Hi Haynes,

thanks for your previous help with the missing SNPs. On another note:

### Does the pipeline output the _number of SNPs assigned to each genotype_ as a summary? 
I could not find it, and also not sure on which column of **cluster_genotypes.vcf**, should I use to extract this information. I guess the total number of positions listed in this file should be each assigned to a genotype.

Why do I care: 
I wonder how close genotypes I can demux? We have an in house H9 hESC line and H9 from HipSci cell line bank – these clones are separated by a ~decade of culturing, and wonder if I can call them apart. 
The number of SNPs assigned to each could give a rough confidence estimate.

Thanks a lot!

**Comment by wheaton5** [comment]
Well, I don't really assign SNPs to clusters at all really. Here is how it works.

Do variant calling. Potentially informative SNPs are ones where we at least saw some cells with ref and some with alt (this is --min_ref and --min_alt). Then for each of those, each cluster gets an allele fraction for each of those (randomly initialized if not using known_genotypes). Then we do a fancy version of E/M (as it has this deterministic annealing aspect, but don't worry about that. Just EM without easily getting stuck in local maxima). So each cell gets a posterior probability of belonging to each cluster and then each cell updates each cluster weighted on that probability. The final allele fractions should be near 0 (homozygous ref), 0.5 (heterozygous), or 1 (homozygous alt). But they won't be exactly that due to doublets, ambient RNA, and error. 

What you are looking for is which SNPs were most informative and what is the minimum number of SNPs that would allow for demultiplexing. I believe both of these questions are NP hard lol as each SNP's power is not independent of the other SNPs. Tho you can make greedy estimates by assuming independence. But also even if you find a set which distinguishes the clusters from each other, you are betting that every cell expresses that locus. For some loci perhaps that is a reasonable assumption. So to do this i think we would first want to look at loci which are expressed in >80% of cells. Then I'd look for private SNPs to each cluster. In your case those will all be heterozygous in one cluster and homozygous in the other clusters.

**Comment by vertesy** [comment]
Thanks a lot for the thorough explanation  & sorry for my ignorance about SNP assignment! 
I will first read again and play with the simpler problems first to get a better understanding, then I will revisit this matter again.
