### ISSUE TITLE
Interpreting cluster outputs

### ISSUE THREAD

**Issue by msto** [wheaton5/souporcell#88]
Hi,

I have a quick question about the outputs produced by the souporcell pipeline. In `clusters.tsv`, what is the significance of assignment being `0/1` vs `1/0` when a barcode has been called a doublet? Similarly, what is the meaning of the assignment (`0`, `1`, `0/1`, or `1/0`) when a barcode has `unassigned` status?

Thanks!

**Comment by yupingz** [comment]
I have the same questions. I couldn't find definition of unassigned cells in the paper.

**Comment by wheaton5** [comment]
Hi. Sorry I didnt see this before. So the unassigned feature was added post publication which is why you don't see it there. There is a posterior probability threshold for assignment which defaults to 0.9. I guess I don't bubble that up to the pipeline level as a parameter and I should do that. Having 0/1 vs 1/0 is just that it will always support one cluster over the other and it lists them in order of support. If it is unassigned it will still list the maximum probability assigned cluster or doublet. I hope this helps.

**Comment by yupingz** [comment]
Thank you, it helps a lot.
